### ISSUE TITLE
First YQL query appears to be broken

### ISSUE THREAD

**Issue by graymalkin** [hollosyt/yourdotahabit#6]
Hia,

The first YQL query appears to be ded, maybe others.

``` javascript
url: "https://query.yahooapis.com/v1/public/yql?q=select%20href%20from%20html%20wher\
e%0A%20url%3D%22" + encodeURIComponent($('#dotabuffurl').val()) + "%2F/matches%22%0A%20%20%20and%20compat%3D%22html5%22%20an\
d%20xpath%3D'%2F%2Fsection%2Farticle%2Fnav%2Fspan%5B8%5D%2Fa'&format=json&callback="
```

``` sql
select href from html where
    url="http://www.dotabuff.com/players/61791495/matches"
    and compat="html5"
    and xpath='//section/article/nav/span[8]/a'
```

Results from that are something like this:

``` json
{
    "query": {
        "count": 0,
        "created": "2015-01-26T18:41:12Z",
        "lang": "en-GB",
        "results": null
    }
}
```

The xpath points to the 'last' button, which looks correct, to me. Any thoughts?

**Comment by graymalkin** [comment]
Ah, upon some further investigation from the Yahoo YQL console, it would appear that Yahoo has been throttled. Your service is too popular ;)

``` sql
select * from html 
    where url="http://www.dotabuff.com/players/61791495/matches"
```

``` json
{
 "query": {
  "count": 0,
  "created": "2015-01-26T18:53:22Z",
  "lang": "en-US",
  "diagnostics": {
   "publiclyCallable": "true",
   "url": [
    {
     "error": "Throttled",
     "execution-start-time": "1",
     "execution-stop-time": "307",
     "execution-time": "306",
     "http-status-code": "429",
     "http-status-message": "Throttled",
     "content": "http://www.dotabuff.com/players/61791495/matches"
    },
    {
     "error": "Throttled",
     "execution-start-time": "1",
     "execution-stop-time": "307",
     "execution-time": "306",
     "http-status-code": "429",
     "http-status-message": "Throttled",
     "content": "http://www.dotabuff.com/players/61791495/matches"
    }
   ],
   "user-time": "307",
   "service-time": "612",
   "build-version": "0.2.212"
  },
  "results": null
 }
}
```

**Comment by hollosyt** [comment]
Yeah, I think I need to switch to the raw dota 2 api, maybe over node or something. I don't want this thing to have to be hosted, would like to be pure client based.

**Comment by graymalkin** [comment]
Yeah :/

I had a go at using js to do the XML scraping, but I can't get the document because of access headers required by js to prevent XSS :(

On 26 Jan 2015 21:55, Tim Hollosy notifications@github.com wrote:

Yeah, I think I need to switch to the raw dota 2 api, maybe over node or something. I don't want this thing to have to be hosted, would like to be pure client based.

**Comment by hollosyt** [comment]
Yeah the XSS is what led me to YQL in the first place, looks like a node wrapper exists for dota 2, not sure how hard it would be to implement. I've never done any node before, but it really just needs to make 1 call to the api to get match history for a steam id.

**Comment by graymalkin** [comment]
062db802e4036dc9abc1c25559272e13b24d9f94 closes this.
